[package]
authors = ["MikiAlex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-scene-raytracing"
version = "0.1.0"

[dependencies]
dyn-clone = "1.0.5"
image = "*"
indicatif = "0.15"
rand = "0.7.3"
rayon = "1.7.0"
statrs = "0.16.0"
tobj = "2.0.3"

arena = {path = "../../utils/arena"}
rendiation-algebra = {path = "../../math/algebra"}
rendiation-color = {path = "../../components/color"}
rendiation-geometry = {path = "../../math/geometry"}
rendiation-renderable-mesh = {path = "../../components/mesh/renderable"}
rendiation-scene-core = {path = "../core"}
rendiation-texture = {path = "../../components/texture/core"}
space-algorithm = {path = "../../components/space"}
tree = {path = "../../utils/tree"}
