[package]
authors = ["MikiAlex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-scene-raytracing"
version = "0.1.0"

[dependencies]
arena = {path = "../../utils/arena"}
arena-graph = {path = "../../utils/arena-graph"}
arena-tree = {path = "../../utils/arena-tree"}
bytemuck = {version = "1.4.1", features = ["derive"]}
log = "0.4"
once_cell = "1.4.0"
rand = "0.7.3"
rendiation-algebra = {path = "../../math/algebra"}
rendiation-geometry = {path = "../../math/geometry"}
rendiation-renderable-mesh = {path = "../../components/mesh/renderable", features = ["webgpu"]}
rendiation-scene-core = {path = "../core"}
rendiation-texture = {path = "../../components/texture/core", features = ["webgpu"]}
space-algorithm = {path = "../../components/space"}
tobj = "2.0.3"
