[package]
authors = ["MikiAlex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-scene-raytracing"
version = "0.1.0"

[dependencies]
dyn-clone = { workspace = true }
image = "*"
indicatif = "0.15"
rand = { workspace = true }
rayon = { workspace = true }
statrs = "0.16.0"
tobj = "2.0.3"

arena = { path = "../../utils/arena" }
rendiation-algebra = { path = "../../math/algebra" }
rendiation-color = { path = "../../components/color" }
rendiation-geometry = { path = "../../math/geometry" }
rendiation-lighting-transport = { path = "../../components/lighting/transport" }
rendiation-mesh-core = { path = "../../components/mesh/core" }
rendiation-scene-core = { path = "../core" }
rendiation-statistics = { path = "../../math/statistics" }
rendiation-texture = { path = "../../components/texture/core" }
space-algorithm = { path = "../../components/space" }
tree = { path = "../../utils/tree" }

[lints]
workspace = true
