[package]
authors = ["MikiAlex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-scene-rendering-gpu-base"
version = "0.1.0"

[dependencies]

fast-hash-collection = { path = "../../../utility/fast-hash-collection" }
rendiation-scene-core-next = { path = "../../core-next" }
reactive = { path = "../../../utility/reactive" }
rendiation-webgpu = { path = "../../../platform/graphics/webgpu" }


[lints]
workspace = true
