[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-device-task-graph"
version = "0.1.0"

[dependencies]
rendiation-shader-derives = { path = "../derive" }
rendiation-shader-api = { path = "../api" }
rendiation-webgpu = { path = "../../platform/graphics/webgpu" }
fast-hash-collection = { path = "../../utility/fast-hash-collection" }
parking_lot = { version = "0.12.1", features = ["send_guard"] }
dyn-clone = { workspace = true }
derivative = { workspace = true }
futures = { workspace = true }

pollster = { workspace = true } # used in examples

[lints]
workspace = true
