[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-lighting-ibl-core"
version = "0.1.0"

[dependencies]
rendiation-algebra = { path = "../../../../math/algebra" }
rendiation-shader-api = { path = "../../../../shader/api" }
rendiation-shader-library = { path = "../../../../shader/library" }
rendiation-texture-core = { path = "../../../texture/core" }
rendiation-lighting-transport = { path = "../../../lighting/transport" }

[lints]
workspace = true
