[package]
name = "rendiation-shadergraph"
version = "0.1.0"
authors = ["mikialex <18516340862@163.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
arena-graph = { path = "../utils/arena-graph" }
rendiation-math = { path = "../math" }
