
[package]
authors = ["MikiAlex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-webgpu-reactive-utils"
version = "0.1.0"

[dependencies]
reactive = { path = "../../../utility/reactive" }
rendiation-shader-api = { path = "../../../shader/api" }
rendiation-webgpu = { path = "../webgpu" }
fast-hash-collection = { path = "../../../utility/fast-hash-collection" }

[lints]
workspace = true
