[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-texture-loader"
version = "0.1.0"

[dependencies]
image = "*"
rendiation-algebra = { path = "../../../math/algebra" }
rendiation-texture-core = { path = "../core" }
thiserror = "1.0.43"

[lints]
workspace = true
