[workspace]
members = [
    "math",
    "math-entity",
    "render-entity",
    "rendiation",
    "render-graph",
    "scene-graph",
    "rendium",
    "rinecraft",
    "rivermesh",
    "noize",
    "rainray",
    "space-indexer"
]

[profile.release]
# Tell `rustc` to optimize for small code size.
# opt-level = 's'

# opt-level = 3