[workspace]
members = [
  "math/algebra",
  "math/geometry",
  "sceno",
  "rainray",
  "utils/arena",
  "utils/arena-graph",
  "utils/arena-tree",
  "components/color",
  "components/controller",
  "components/mesh/renderable",
  "components/mesh/editable",
  "components/texture/core",
  "components/texture/packer",
  "components/texture/generative",
  "components/space",
  "webgpu",
  "viewer"
]
