[workspace]
members = [
  "math/algebra",
  "math/geometry",
  "utils/incremental",
  "utils/incremental-derive",
  "utils/reactive",
  "utils/reactive-incremental",
  "utils/arena",
  "utils/dyn-downcast",
  "utils/arena-graph",
  "utils/tree",
  "utils/storage",
  "utils/abstract-tree",
  "utils/abstract-graph",
  "utils/fast-hash-collection",
  "components/animation",
  "components/color",
  "components/controller",
  "components/mesh/renderable",
  "components/mesh/editable",
  "components/mesh/generator",
  "components/texture/core",
  "components/texture/types",
  "components/texture/packer",
  "components/texture/gpu-system",
  "components/texture/generative",
  "components/space",
  "components/fontext",
  "components/canvas",
  "interphaser",
  "shader/graph",
  "shader/derive",
  "shader/derive-shared",
  "shader/language/wgsl/parser",
  "shader/language/wgsl/derive",
  "shader/backends/naga",
  "scene/core",
  "scene/webgpu",
  "scene/raytracing",
  "scene/interaction",
  "scene/io/obj/loader",
  "scene/io/gltf/loader",
  "scene/io/gltf/exporter",
  "viewer",
  "platform/graphics/webgpu",
  "platform/graphics/vulkan",
]

# https://doc.rust-lang.org/nightly/cargo/reference/features.html#feature-resolver-version-2
resolver = "2"


# https://doc.rust-lang.org/cargo/reference/profiles.html

# currently our implementation not provide panic safety and recovery
# and also enable unwind is bad for performance

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
