[workspace]
members = [
  "math/algebra",
  "math/geometry",
  "utils/incremental",
  "utils/incremental-derive",
  "utils/incremental-ui-prototype",
  "utils/reactive",
  "utils/arena",
  "utils/arena-graph",
  "utils/tree",
  "utils/storage",
  "utils/abstract-tree",
  "utils/abstract-graph",
  "components/color",
  "components/controller",
  "components/mesh/renderable",
  "components/mesh/editable",
  "components/mesh/generator",
  "components/texture/core",
  "components/texture/types",
  "components/texture/packer",
  "components/texture/generative",
  "components/space",
  "components/fontext",
  "components/canvase",
  "interphaser",
  "shader/graph",
  "shader/testing",
  "shader/derive",
  "shader/derive-shared",
  "shader/language/wgsl/parser",
  "shader/language/wgsl/derive",
  "shader/language/wgsl/codegen-graph",
  "scene/core",
  "scene/webgpu",
  "scene/raytracing",
  "scene/io/gltf/loader",
  "viewer",
  "webgpu",
]

# https://doc.rust-lang.org/nightly/cargo/reference/features.html#feature-resolver-version-2
resolver = "2"
