[workspace]
members = [
    "math",
    "math-entity",
    "render-entity",
    "rendiation",
    "rendiation-derives",
    "render-graph",
    "scene-graph",
    "rendium",
    "rinecraft",
    "rivermesh",
    "noize",
    "rainray",
    "space-indexer",
    "mesh-buffer",
    "utils/arena",
]
