[workspace]
members = [
  "math",
  "math-entity",
  "render-entity",
  "ral",
  "webgpu",
  "webgl",
  "render-graph",
  "scene-graph",
  "shader-graph",
  "shader-graph-derives",
  "shader-library",
  "nyxt-viewer",
  "rendium",
  "rinecraft",
  "rivermesh",
  "noize",
  "rainray",
  "space-indexer",
  "mesh-buffer",
  "utils/arena",
  "utils/arena-graph",
  "utils/arena-tree",
]
