[workspace]
members = [
    "math",
    "math-entity",
    "render-entity",
    "ral",
    "webgpu",
    "webgl",
    "render-graph",
    "scene-graph",
    "ecscene",
    "shader-graph",
    "shader-graph-derives",
    "shader-library",
    "rendium",
    "rinecraft",
    "rivermesh",
    "noize",
    "rainray",
    "space-indexer",
    "mesh-buffer",
    "utils/arena",
    "utils/arena-graph",
    "utils/arena-tree",
]
