[workspace]
members = [
    "math",
    "math-entity",
    "render-entity",
    "wasm",
    "rendiation",
]

[profile.release]
# Tell `rustc` to optimize for small code size.
# opt-level = 's'

# opt-level = 3