[workspace]
members = [
  "math",
  "math-entity",
  "render-entity",
  "ral/core",
  "ral/backend/webgpu",
  "ral/backend/webgl",
  "render-graph",
  "scene-graph",
  "shader-graph",
  "derives",
  "shader-library",
  "nyxt/viewer",
  "nyxt/core",
  "rendium",
  "voxland",
  "rivermesh",
  "noize",
  "rainray",
  "space-indexer",
  "mesh-buffer",
  "utils/arena",
  "utils/arena-graph",
  "utils/arena-tree",
]
