[workspace]
members = [
  "math/algebra",
  "math/geometry",
  "mesh/renderable",
  "mesh/editable",
  "texture/core",
  "texture/packer",
  "texture/generative",
  # "ral/core",
  # "ral/resource",
  # "ral/backend/webgpu",
  # "ral/backend/webgl",
  # "render-graph",  # "shader-graph",  # "shader-library", 
  # "derives",
  # "voxland",
  "scene/core", 
  "rainray",
  "space-algorithm",
  "utils/arena",
  "utils/arena-graph",
  "utils/arena-tree",
  "components/color",
  "components/controller",
]
