[workspace]
members = [
  "math/algebra",
  "math/geometry",
  "rainray",
  "utils/arena",
  "utils/arena-graph",
  "utils/arena-tree",
  "utils/storage",
  "components/color",
  "components/controller",
  "components/mesh/renderable",
  "components/mesh/editable",
  "components/texture/core",
  "components/texture/types",
  "components/texture/packer",
  "components/texture/generative",
  "components/space",
  "components/fontext",
  "interphaser",
  "shader/graph",
  "shader/derive",
  "shader/parser/wgsl",
  "scene",
  "viewer",
  "webgpu",
]

# https://doc.rust-lang.org/nightly/cargo/reference/features.html#feature-resolver-version-2
resolver = "2"
