[package]
edition = "2021"
name = "rendiation-algebra"
version = "0.1.0"

[dependencies]
bytemuck = {version = "1.4.1", features = ["derive"]}
num-traits = "0.2"
paste = "1.0.2"

[dev-dependencies]
cgmath = "0.18.0"
