[package]
edition = "2018"
name = "rendiation-algebra"
version = "0.1.0"

[features]
swizzle = ["paste"]

[dependencies]
bytemuck = "1.4.1"
num-traits = "0.2"
paste = {version = "1.0.2", optional = true}
