[package]
edition = "2021"
name = "rendiation-algebra"
version = "0.1.0"

[dependencies]
bytemuck = { workspace = true, features = ["derive"] }
num-traits = "0.2"
paste = { workspace = true }

incremental = { path = "../../utils/incremental" }

[dev-dependencies]
cgmath = "0.18.0"

[lints]
workspace = true
