[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-device-parallel-compute"
version = "0.1.0"

[dependencies]
rendiation-algebra = { path = "../../math/algebra" }
rendiation-shader-derives = { path = "../derive" }
rendiation-shader-api = { path = "../api" }
rendiation-webgpu = { path = "../../platform/graphics/webgpu" }

[lints]
workspace = true
