[package]
edition = "2021"
name = "rendiation-scene-gltf-loader"
version = "0.0.1"

[dependencies]
bytemuck = { version = "1.4.1", features = ["derive"] }
gltf = "1.2.0"
half = "*"
rendiation-algebra = { path = "../../../../math/algebra" }
rendiation-geometry = { path = "../../../../math/geometry" }
rendiation-renderable-mesh = { path = "../../../../components/mesh/renderable" }
rendiation-scene-core = { path = "../../../core" }
rendiation-texture = { path = "../../../../components/texture/core" }
rendiation-shader-api = { path = "../../../../shader/api" }
fast-hash-collection = { path = "../../../../utils/fast-hash-collection" }
