[package]
edition = "2021"
name = "rendiation-scene-gltf-loader"
version = "0.0.1"

[dependencies]
gltf = "1.0.0"
rendiation-algebra = {path = "../../../../math/algebra"}
rendiation-color = {path = "../../../../components/color"}
rendiation-scene-webgpu = {path = "../../../webgpu"}
rendiation-texture = {path = "../../../../components/texture/core"}
webgpu = {package = "rendiation-webgpu", path = "../../../../webgpu"}
