[package]
edition = "2021"
name = "rendiation-scene-gltf-loader"
version = "0.0.1"

[dependencies]
bytemuck = {version = "1.4.1", features = ["derive"]}
gltf = "1.0.0"
half = "*"
rendiation-algebra = {path = "../../../../math/algebra"}
rendiation-geometry = {path = "../../../../math/geometry"}
rendiation-renderable-mesh = {path = "../../../../components/mesh/renderable"}
rendiation-scene-core = {path = "../../../core"}
rendiation-texture = {path = "../../../../components/texture/core"}
shadergraph = {path = "../../../../shader/graph"}
