[package]
edition = "2021"
name = "rendiation-scene-gltf-loader"
version = "0.0.1"

[dependencies]
gltf = "1.0.0"
rendiation-algebra = {path = "../../../../math/algebra"}
rendiation-scene-core = {path = "../../../core"}
rendiation-texture = {path = "../../../../components/texture/core"}
rendiation-renderable-mesh = {path = "../../../../components/mesh/renderable"}
shadergraph = {path = "../../../../shader/graph"}
webgpu = {package = "rendiation-webgpu", path = "../../../../webgpu"}
