[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-shader-library"
version = "0.1.0"

[dependencies]
rendiation-algebra = { path = "../../math/algebra" }
rendiation-shader-api = { path = "../api" }

[lints]
workspace = true
