[package]
authors = ["MikiAlex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-mesh-gpu-system"
version = "0.1.0"

[dependencies]
bytemuck = { workspace = true, features = ["derive"] }
fast-hash-collection = { path = "../../../utility/fast-hash-collection" }
futures = { workspace = true }
pin-project = { workspace = true }
rendiation-shader-api = { path = "../../../shader/api" }
rendiation-webgpu = { path = "../../../platform/graphics/webgpu" }
slab = "0.4.8"
xalloc = "0.2.7"

[lints]
workspace = true
