[package]
authors = ["MikiAlex <18516340862@163.com>"]
edition = "2018"
name = "rendiation-texture"
version = "0.1.0"

[dependencies]
rendiation-algebra = {path = "../../math/algebra"}
rendiation-geometry = {path = "../../math/geometry"}
rendiation-ral = {path = "../../ral/core"}

image = "*"
