[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-canvas"
version = "0.1.0"

[dependencies]
rendiation-algebra = {path = "../../math/algebra"}
rendiation-geometry = {path = "../../math/geometry"}
rendiation-color = {path = "../color"}
bytemuck = "1.4.1"
