[package]
edition = "2021"
name = "tree"
version = "0.0.1"

[dependencies]
futures = { workspace = true }
incremental = { path = "../incremental" }
reactive = { path = "../reactive" }
reactive-incremental = { path = "../reactive-incremental" }
rendiation-abstract-tree = { path = "../abstract-tree" }
storage = { path = "../storage" }
parking_lot = { version = "0.12.1", features = ["send_guard"] }

[lints]
workspace = true
