[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2018"
name = "nyxt-viewer"
version = "0.1.0"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["cdylib", "rlib"]

# [build]
# rustflags = "--csefg=web_sys_unstable_apis"

[features]
default = ["nyxt", "webgl"]
nyxt = []
webgl = []


[dependencies]
nyxt-core = {path = "../core"}

rendiation-math = {path = "../../math"}
rendiation-math-entity = {path = "../../math-entity"}
rendiation-mesh-buffer = {path = "../../mesh-buffer", features = ["shadergraph"]}
rendiation-ral = {path = "../../ral/core"}
rendiation-render-entity = {path = "../../render-entity"}
rendiation-scenegraph = {path = "../../scene-graph"}
rendiation-shader-library = {path = "../../shader-library", features = ["nyxt", "webgl"]}
rendiation-shadergraph = {path = "../../shader-graph"}
space-indexer = {path = "../../space-indexer"}

bytemuck = "1.4.1"
console_error_panic_hook = "0.1.6"
js-sys = "0.3.45"
wasm-bindgen = {version = "0.2.68"}

rendiation-webgl = {path = "../../ral/backend/webgl"}

arena = {path = "../../utils/arena"}
arena-tree = {path = "../../utils/arena-tree"}
once_cell = "1.4.0"
