[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2018"
name = "shadergraph-testing"
version = "0.1.0"

[dependencies]
shadergraph = {path = "../graph"}
wgsl-codegen-graph = {path = "../language/wgsl/codegen-graph"}
glsl-shader-derives = {path = "../language/glsl/derive"}
naga = {version = "*", features = ["wgsl-in"]}
