[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2021"
name = "shadergraph-testing"
version = "0.1.0"

[dependencies]
naga = {version = "*", features = ["wgsl-in"]}
shadergraph = {path = "../graph"}
wgpu-types = "0.15.0"
wgsl-codegen-graph = {path = "../language/wgsl/codegen-graph"}
wgsl-shader-derives = {path = "../language/wgsl/derive"}
