[package]
edition = "2021"
name = "reactive"
version = "0.0.1"

[dependencies]
futures = "0.3.25"
storage = { path = "../storage" }
pin-project = "1.0.12"
fast-hash-collection = { path = "../fast-hash-collection" }
crossbeam-queue = "0.3.8"
slab = "0.4.8"

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
name = "reactive"
harness = false
