[package]
edition = "2018"
name = "rendiation-math"
version = "0.1.0"

[features]
swizzle = ["paste"]

[dependencies]
paste = { version = "1.0.2", optional = true }
bytemuck = "1.4.1"
num-traits = "0.2"

wasm-bindgen = {version = "0.2.68"}