[package]
authors = ["MikiAlex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-lighting-punctual"
version = "0.1.0"

[dependencies]
rendiation-algebra = { path = "../../../math/algebra" }
rendiation-shader-api = { path = "../../../shader/api" }
rendiation-lighting-transport = { path = "../transport" }

[lints]
workspace = true
