[package]
authors = ["MikiAlex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-texture"
version = "0.1.0"

[dependencies]
image = "*"
rendiation-algebra = {path = "../../../math/algebra"}
rendiation-geometry = {path = "../../../math/geometry"}
rendiation-texture-types = {path = "../types"}
rendiation-webgpu = {path = "../../../webgpu", optional = true}
incremental = {path = "../../../utils/incremental"}

[features]
webgpu = ["rendiation-webgpu"]
