[package]
authors = ["MikiAlex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-gpu-lighting-system"
version = "0.1.0"

[dependencies]
rendiation-algebra = { path = "../../../../math/algebra" }
rendiation-shader-api = { path = "../../../../shader/api" }
rendiation-webgpu = { path = "../../../../platform/graphics/webgpu" }
rendiation-lighting-transport = { path = "../../transport" }


[lints]
workspace = true
