[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2018"
name = "rendiation-ral"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
arena = {path = "../utils/arena"}
wasm-bindgen = {version = "0.2.68"}
