[package]
authors = ["MikiAlex <18516340862@163.com>"]
edition = "2018"
name = "rendiation-texture-packer"
version = "0.1.0"

[dependencies]
rendiation-math = {path = "../math"}
rendiation-math-entity = {path = "../math-entity"}
