[package]
authors = ["MikiAlex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-mesh-gpu-system"
version = "0.1.0"

[dependencies]
rendiation-webgpu = { path = "../../../platform/graphics/webgpu" }
rendiation-shader-api = { path = "../../../shader/api" }
fast-hash-collection = { path = "../../../utils/fast-hash-collection" }
xalloc = "0.2.7"
pin-project = "1.0.12"
futures = "0.3.25"
bytemuck = "1.4.1"
slab = "0.4.8"
