[package]
edition = "2021"
name = "rendiation-generative-texture"
version = "0.0.1"

[dependencies]
rendiation-algebra = { path = "../../../math/algebra" }
rendiation-texture = { path = "../core" }

[dev-dependencies]
image = "*"

[lints]
workspace = true
