[package]
authors = ["MikiAlex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-scene-webgpu"
version = "0.1.0"

[dependencies]
anymap = "0.12.1"
arena = { path = "../../utils/arena" }
arena-graph = { path = "../../utils/arena-graph" }
bitflags = "2.2"
bytemuck = { version = "1.4.1", features = ["derive"] }
dyn-clone = "1.0.5"
futures = "0.3.25"
incremental = { path = "../../utils/incremental" }
fast-hash-collection = { path = "../../utils/fast-hash-collection" }
linked-hash-map = "0.5.4"
log = "0.4"
once_cell = "1.4.0"
pin-project = "1.0.12"
rand = "0.7.3"
rendiation-algebra = { path = "../../math/algebra" }
rendiation-color = { path = "../../components/color" }
rendiation-geometry = { path = "../../math/geometry" }
rendiation-mesh-core = { path = "../../components/mesh/core" }
rendiation-lighting-transport = { path = "../../components/lighting/transport" }
rendiation-lighting-ibl-core = { path = "../../components/lighting/ibl/core" }
rendiation-texture-gpu-system = { path = "../../components/texture/gpu-system" }
rendiation-mesh-gpu-system = { path = "../../components/mesh/gpu-system" }
rendiation-scene-core = { path = "../core" }
rendiation-texture = { path = "../../components/texture/core" }
rendiation-shader-library = { path = "../../shader/library" }
tree = { path = "../../utils/tree" }

rendiation-shader-api = { path = "../../shader/api" }

reactive = { path = "../../utils/reactive" }
webgpu = { package = "rendiation-webgpu", path = "../../platform/graphics/webgpu" }
