[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-scene-debug-helper"
version = "0.1.0"

[dependencies]
rendiation-algebra = { path = "../../math/algebra" }
rendiation-scene-core = { path = "../../scene/core" }
rendiation-shader-api = { path = "../../shader/api" }
database = { path = "../../utility/database" }
reactive = { path = "../../utility/reactive" }
rendiation-webgpu = { path = "../../platform/graphics/webgpu" }
rendiation-scene-rendering-gpu-gles = { path = "../../scene/rendering/gpu-gles" }
rendiation-state-override = { path = "../state-override" }
winit = { workspace = true }

[lints]
workspace = true
