[package]
name = "rendiation-scenegraph"
version = "0.1.0"
authors = ["mikialex <18516340862@163.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]


[features]
wgpu = ["rendiation", "rendiation-derives", "rendiation-mesh-buffer/wgpu"]
webgl = []

[dependencies]
wasm-bindgen = { version = "0.2.62" }
js-sys = "0.3.39"
arena = { path = "../utils/arena" }
rendiation-math = { path = "../math" }
rendiation-math-entity = { path = "../math-entity" }
rendiation-render-entity = { path = "../render-entity" }
rendiation-mesh-buffer = { path = "../mesh-buffer" }

rendiation = { path = "../rendiation", optional = true}
rendiation-derives = { path = "../rendiation-derives", optional = true }

[dependencies.web-sys]
version = "0.3.39"
features = [
  'Document',
  'Element',
  'HtmlCanvasElement',
  'WebGlBuffer',
  'WebGl2RenderingContext',
  'WebGlProgram',
  'WebGlUniformLocation',
  'WebGlShader',
  'WebGlFramebuffer',
  'Window',
]
