[package]
name = "rendiation-scenegraph"
version = "0.1.0"
authors = ["mikialex <18516340862@163.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = { version = "0.2.62" }
js-sys = "0.3.39"
generational-arena = { version = "0.2" }
rendiation-math = { path = "../math" }
rendiation-math-entity = { path = "../math-entity" }
rendiation-render-entity = { path = "../render-entity" }
rendiation-mesh-buffer = { path = "../mesh-buffer", features = ["wgpu"] }

rendiation = { path = "../rendiation"}
rendiation-derives = { path = "../rendiation-derives" }

[dependencies.web-sys]
version = "0.3.39"
features = [
  'Document',
  'Element',
  'HtmlCanvasElement',
  'WebGlBuffer',
  'WebGlRenderingContext',
  'WebGlProgram',
  'WebGlUniformLocation',
  'WebGlShader',
  'WebGlFramebuffer',
  'Window',
]
