[package]
name = "rendiation-scenegraph"
version = "0.1.0"
authors = ["mikialex <18516340862@163.com>"]
edition = "2018"

[dependencies]
rendiation = { path = "../rendiation" }
rendiation-math = { path = "../math" }
rendiation-math-entity = { path = "../math-entity" }
rendiation-render-entity = { path = "../render-entity" }
rendiation-util = { path = "../util" }
rendiation-marco = { path = "../marco" }
generational-arena = { version = "0.2" }