[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-light-transport"
version = "0.1.0"

[dependencies]
rendiation-algebra = { path = "../../../math/algebra" }
rendiation-statistics = { path = "../../../math/statistics" }
rendiation-shader-api = { path = "../../../shader/api" }
