[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-shader-api"
version = "0.1.0"

[dependencies]
bytemuck = { version = "1.4.1", features = ["derive"] }
once_cell = "1.4.0"
paste = "1.0.2"
rendiation-algebra = { path = "../../math/algebra" }
fast-hash-collection = { path = "../../utils/fast-hash-collection" }
rendiation-shader-derives = { path = "../derive" }
wgpu-types = "0.17"
