[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2018"
name = "rendiation-controller"
version = "0.1.0"

[dependencies]
rendiation-algebra = {path = "../../math/algebra"}
rendiation-geometry = {path = "../../math/geometry"}
