[package]
edition = "2021"
name = "reuse-pool"
version = "0.0.1"

[dependencies]
fast-hash-collection = { path = "../fast-hash-collection" }
parking_lot = { workspace = true }

[lints]
workspace = true
