[package]
authors = ["MikiAlex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-webgpu"
version = "0.1.0"

[dependencies]
bytemuck = { workspace = true, features = ["derive"] }
dyn-downcast = { path = "../../../utility/dyn-downcast" }
heap-tools = { path = "../../../utility/heap-tools" }
fast-hash-collection = { path = "../../../utility/fast-hash-collection" }
futures = { workspace = true }
naga = { version = "22", features = ["wgsl-out"] }
reactive = { path = "../../../utility/reactive" }
rendiation-algebra = { path = "../../../math/algebra" }
rendiation-shader-api = { path = "../../../shader/api" }
rendiation-shader-backend-naga = { path = "../../../shader/backends/naga" }
rendiation-texture-types = { path = "../../../content/texture/types" }
thiserror = { workspace = true }
wgpu = { version = "22", features = ["naga-ir"] }
wgpu-types = "22"
winit = { workspace = true }
xalloc = "0.2.7"
slab = "0.4.8"


pollster = { workspace = true } # used in examples

[features]
webgl = ["wgpu/webgl"]

[lints]
workspace = true
