[package]
authors = ["MikiAlex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-webgpu"
version = "0.1.0"

[dependencies]
bytemuck = { version = "1.4.1", features = ["derive"] }
futures = "0.3.25"
thiserror = "1.0.43"
dyn-downcast = { path = "../../../utils/dyn-downcast" }
reactive = { path = "../../../utils/reactive" }
fast-hash-collection = { path = "../../../utils/fast-hash-collection" }
rendiation-algebra = { path = "../../../math/algebra" }
rendiation-texture-types = { path = "../../../components/texture/types" }
rendiation-shader-api = { path = "../../../shader/api" }
rendiation-shader-backend-naga = { path = "../../../shader/backends/naga" }
typed-arena = "2.0.1"
wgpu = { version = "0.17", features = ["naga"] }
wgpu-types = "0.17"
winit = { version = "0.27.1" }
naga = { version = "0.13.0", features = ["wgsl-out"] }

[features]
webgl = ["wgpu/webgl"]
