[package]
authors = ["MikiAlex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-scene-core"
version = "0.1.0"

[dependencies]
anymap = "0.12.1"
arena = {path = "../../utils/arena"}
bitflags = "*"
bytemuck = {version = "1.4.1", features = ["derive"]}
dyn-clone = "1.0.5"
dyn-downcast = {path = "../../utils/dyn-downcast"}
futures = "0.3.25"
incremental = {path = "../../utils/incremental"}
log = "0.4"
once_cell = "1.4.0"
paste = "1.0.2"
pin-project = "1.0.12"
reactive = {path = "../../utils/reactive"}
rendiation-algebra = {path = "../../math/algebra"}
rendiation-animation = {path = "../../components/animation"}
rendiation-geometry = {path = "../../math/geometry"}
rendiation-renderable-mesh = {path = "../../components/mesh/renderable"}
rendiation-texture = {path = "../../components/texture/core"}
smallvec = "1.9.0"
tree = {path = "../../utils/tree"}
