[package]
authors = ["MikiAlex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-scene-core"
version = "0.1.0"

[dependencies]
anymap = "0.12.1"
arena = {path = "../../utils/arena"}
arena-tree = {path = "../../utils/arena-tree"}
bytemuck = {version = "1.4.1", features = ["derive"]}
log = "0.4"
once_cell = "1.4.0"
rendiation-algebra = {path = "../../math/algebra"}
rendiation-geometry = {path = "../../math/geometry"}
rendiation-renderable-mesh = {path = "../../components/mesh/renderable"}
rendiation-texture = {path = "../../components/texture/core"}
