[package]
authors = ["MikiAlex <18516340862@163.com>"]
edition = "2021"
name = "space-algorithm"
version = "0.1.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
harness = false
name = "bvh"

[dependencies]

rendiation-abstract-tree = {path = "../../utils/abstract-tree"}
rendiation-algebra = {path = "../../math/algebra"}
rendiation-geometry = {path = "../../math/geometry"}

log = "0.4"
rand = "0.8.5"
rand_chacha = "0.3.1"
