[package]
authors = ["MikiAlex <18516340862@163.com>"]
edition = "2021"
name = "space-algorithm"
version = "0.1.0"

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
harness = false
name = "bvh"

[dependencies]

rendiation-abstract-tree = { path = "../../utils/abstract-tree" }
rendiation-algebra = { path = "../../math/algebra" }
rendiation-geometry = { path = "../../math/geometry" }

log = { workspace = true }
rand = "0.8.5"

[lints]
workspace = true
