[package]
authors = ["MikiAlex <18516340862@163.com>"]
edition = "2018"
name = "viewer"
version = "0.1.0"

[dependencies]
arena = {path = "../utils/arena"}
arena-graph = {path = "../utils/arena-graph"}
arena-tree = {path = "../utils/arena-tree"}
bytemuck = "1.4.1"
env_logger = "0.8.4"
futures = "0.3.15"
glyph_brush = "0.7"
image = "*"
log = "0.4"
once_cell = "1.4.0"
rendiation-algebra = {path = "../math/algebra"}
rendiation-controller = {path = "../components/controller"}
rendiation-geometry = {path = "../math/geometry"}
rendiation-renderable-mesh = {path = "../components/mesh/renderable"}
rendiation-texture = {path = "../components/texture/core"}
wgpu = "0.9"
winit = {version = "0.24.0"}
