[package]
authors = ["MikiAlex <18516340862@163.com>"]
edition = "2018"
name = "viewer"
version = "0.1.0"

[dependencies]
arena = {path = "../utils/arena"}
arena-graph = {path = "../utils/arena-graph"}
arena-tree = {path = "../utils/arena-tree"}
once_cell = "1.4.0"
rendiation-algebra = {path = "../math/algebra"}
rendiation-geometry = {path = "../math/geometry"}
rendiation-renderable-mesh = {path = "../components/mesh/renderable"}
rendiation-texture = {path = "../components/texture/core"}
wgpu = "0.7.1"
winit = {version = "0.24.0"}
futures = "0.3.15"