[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2018"
name = "shadergraph"
version = "0.1.0"

[dependencies]
once_cell = "1.4.0"
paste = "1.0.2"
dyn-clone = "1.0.4"
rendiation-algebra = {path = "../../math/algebra"}
arena-graph = {path = "../../utils/arena-graph"}

shader-derives = {path = "../derive"}