[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2018"
name = "shadergraph"
version = "0.1.0"

[dependencies]
arena-graph = {path = "../../utils/arena-graph"}
bytemuck = {version = "1.4.1", features = ["derive"]}
memoffset = "0.6"
once_cell = "1.4.0"
paste = "1.0.2"
rendiation-algebra = {path = "../../math/algebra"}
shader-derives = {path = "../derive"}
wgpu-types = "*"
