[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-barycentric-solid-line"
version = "0.1.0"

[dependencies]
rendiation-algebra = { path = "../../math/algebra" }
rendiation-geometry = { path = "../../math/geometry" }
rendiation-webgpu = { path = "../../platform/graphics/webgpu" }
rendiation-shader-api = { path = "../../shader/api" }
rendiation-mesh-core = { path = "../../content/mesh/core" }
rendiation-scene-rendering-gpu-gles = { path = "../../scene/rendering/gpu-gles" }
winit = { workspace = true }
bytemuck = { workspace = true, features = ["derive"] }
dyn-downcast = { path = "../../utility/dyn-downcast" }

[lints]
workspace = true
