[package]
name = "rainray"
version = "0.1.0"
authors = ["MikiAlex <18516340862@163.com>"]
edition = "2018"

[dependencies]
image = "*"
rand = "0.7.3"
indicatif = "0.15"
rayon = "1.5.0"

rendiation-math = { path = "../math" }
rendiation-math-entity = { path = "../math-entity" }
rendiation-render-entity = {path = "../render-entity"}
arena-tree = {path = "../utils/arena-tree"}
