[package]
authors = ["MikiAlex <18516340862@163.com>"]
edition = "2018"
name = "rainray"
version = "0.1.0"

[dependencies]
image = "*"
indicatif = "0.15"
rand = "0.7.3"
rayon = "1.5.0"
tobj = "2.0.3"

arena-tree = {path = "../utils/arena-tree"}
rendiation-algebra = {path = "../math/algebra"}
rendiation-geometry = {path = "../math/geometry"}
rendiation-mesh-buffer = {path = "../mesh-buffer"}
rendiation-render-entity = {path = "../render-entity"}
space-indexer = {path = "../space-indexer"}
