[package]
name = "rendiation-webgpu"
version = "0.1.0"
authors = ["mikialex <18516340862@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
glsl-spirv = ["glsl-to-spirv"]
shadergraph = ["rendiation-shadergraph"]

[dependencies]
wgpu = "0.6.0"
glsl-to-spirv = {version = "0.1", optional = true}

rendiation-math = { path = "../../../math" }
rendiation-math-entity = { path = "../../../math-entity" }
rendiation-render-entity = { path = "../../../render-entity" }

rendiation-ral = { path = "../../core" }
rendiation-shadergraph = {path = "../../../shader-graph", optional = true}