[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2018"
name = "rendiation-scenegraph"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
rendergraph = ["rendiation-rendergraph"]
webgpu = ["rendiation-webgpu"]
# nyxt = ["nyxt-core"]

[dependencies]
arena = {path = "../utils/arena"}
js-sys = "0.3.45"
once_cell = "1.4.0"
rendiation-algebra = {path = "../math/algebra"}
rendiation-derives = {path = "../derives"}
rendiation-geometry = {path = "../math/geometry"}
rendiation-mesh-buffer = {path = "../mesh-buffer"}
rendiation-ral = {path = "../ral/core"}
rendiation-render-entity = {path = "../render-entity"}
rendiation-shadergraph = {path = "../shader-graph"}
wasm-bindgen = {version = "0.2.68"}

rendiation-rendergraph = {path = "../render-graph", optional = true}
rendiation-webgpu = {path = "../ral/backend/webgpu", optional = true}

arena-tree = {path = "../utils/arena-tree"}
