[package]
name = "rinecraft"
version = "0.1.0"
authors = ["mikialex <18516340862@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
env_logger = "0.7"
image = "*"
noise = "0.6"
serde = { version = "1.0.105", features = ["derive"] }
futures = "0.3"
tokio = { version = "0.2", features = ["full"] }

rendiation-math = { path = "../math" }
rendiation-math-entity = { path = "../math-entity" }
rendiation-render-entity = { path = "../render-entity" }
rendiation-mesh-buffer = { path = "../mesh-buffer", features = ["webgpu", "shader-graph"] }
rendiation-webgpu = { path = "../webgpu" }
rendium = { path = "../rendium" }

rendiation-scenegraph = { path = "../scene-graph", features = ["webgpu"] }
rendiation-rendergraph = { path = "../render-graph", features = ["webgpu"] }

once_cell = "1.4.0"
rendiation-shadergraph = { path = "../shader-graph" }
rendiation-shadergraph-derives = { path = "../shader-graph-derives" }
rendiation-shader-library = { path = "../shader-library" }