[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-lighting-ibl-cli"
version = "0.1.0"


[dependencies]
rendiation-webgpu = { path = "../../../../platform/graphics/webgpu" }
rendiation-lighting-ibl-gpu = { path = "../gpu" }
rendiation-texture = { path = "../../../texture/core" }
