[package]
authors = ["MikiAlex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-texture-gpu-system"
version = "0.1.0"

[dependencies]
rendiation-shader-api = { path = "../../../shader/api" }
rendiation-webgpu = { path = "../../../platform/graphics/webgpu" }
slab = "0.4.8"
futures = "0.3.25"
