[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-scene-obj-loader"
version = "0.1.0"

[dependencies]
image = "*"
rendiation-algebra = { path = "../../../../math/algebra" }
rendiation-mesh-core = { path = "../../../../components/mesh/core" }
rendiation-scene-core = { path = "../../../core" }
rendiation-texture = { path = "../../../../components/texture/core" }
smallvec = { workspace = true }
thiserror = "1.0.43"
tobj = "4.0.0"
