[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-scene-obj-loader"
version = "0.1.0"

[dependencies]
image = "*"
database = { path = "../../../../utility/database" }
reactive = { path = "../../../../utility/reactive" }
rendiation-algebra = { path = "../../../../math/algebra" }
rendiation-mesh-core = { path = "../../../../content/mesh/core" }
rendiation-scene-core = { path = "../../../core" }
rendiation-scene-io-texture-loader = { path = "../../texture/loader" }
rendiation-texture-core = { path = "../../../../content/texture/core" }
smallvec = { workspace = true }
thiserror = "1.0.43"
tobj = "4.0.0"

[lints]
workspace = true
