[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-lighting-ibl"
version = "0.1.0"

[dependencies]
rendiation-algebra = { path = "../../../math/algebra" }
rendiation-shader-api = { path = "../../../shader/api" }
rendiation-texture = { path = "../../texture/core" }

[dev-dependencies]
image = "*"
