[package]
edition = "2021"
name = "reactive-incremental"
version = "0.0.1"

[dependencies]
dyn-downcast = { path = "../dyn-downcast" }
fast-hash-collection = { path = "../fast-hash-collection" }
futures = { workspace = true }
pin-project = { workspace = true }
heap-tools = { path = "../heap-tools" }
incremental = { path = "../incremental" }
reactive = { path = "../reactive" }
storage = { path = "../storage" }
smallvec = { workspace = true }
tracing = { workspace = true }
rayon = { workspace = true }
dashmap = { workspace = true }


# we use it's rwlock to avoid recursive read deadlock
parking_lot = { version = "0.12.1", features = ["send_guard"] }
