[package]
edition = "2021"
name = "reactive-incremental"
version = "0.0.1"

[dependencies]
dyn-downcast = {path = "../dyn-downcast"}
futures = {workspace = true}
heap-tools = {path = "../heap-tools"}
incremental = {path = "../incremental"}
reactive = {path = "../reactive"}
storage = {path = "../storage"}
