[package]
name = "rendiation-shader-library"
version = "0.1.0"
authors = ["mikialex <18516340862@163.com>"]
edition = "2018"

[dependencies]
rendiation-math = { path = "../math" }
rendiation-shadergraph = { path = "../shader-graph" }
rendiation-shadergraph-derives = { path = "../shader-graph-derives" }
