[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2018"
name = "rendiation-shader-library"
version = "0.1.0"

[features]
wasm = ["wasm-bindgen"]

[dependencies]
once_cell = "1.4.0"
rendiation-math = {path = "../math"}
rendiation-ral = {path = "../ral"}
rendiation-shadergraph = {path = "../shader-graph"}
rendiation-shadergraph-derives = {path = "../shader-graph-derives"}
rendiation-webgpu = {path = "../webgpu"}
rendiation-webgl = {path = "../webgl"}

wasm-bindgen = {version = "0.2.68", optional = true}