[package]
authors = ["MikiAlex <18516340862@163.com>"]
edition = "2018"
name = "interphaser"
version = "0.1.0"

[dependencies]
bytemuck = {version = "1.4.1", features = ["derive"]}
glyph_brush = "0.7"
image = "*"
log = "0.4"
rendiation-algebra = {path = "../math/algebra"}
rendiation-renderable-mesh = {path = "../components/mesh/renderable"}
rendiation-texture = {path = "../components/texture/core"}
rendiation-webgpu = {path = "../webgpu"}
wgpu = "0.9"
winit = {version = "0.24.0"}
