[package]
authors = ["MikiAlex <18516340862@163.com>"]
edition = "2021"
name = "interphaser"
version = "0.1.0"

[dependencies]
arena = {path = "../utils/arena"}
bytemuck = {version = "1.4.1", features = ["derive"]}
font-loader = "0.11.0"
glyph_brush = "0.7"
image = "*"
linked-hash-map = "0.5.4"
log = "0.4"
# nfd = "0.0.4"
rendiation-algebra = {path = "../math/algebra"}
rendiation-color = {path = "../components/color"}
rendiation-geometry = {path = "../math/geometry"}
rendiation-renderable-mesh = {path = "../components/mesh/renderable"}
rendiation-texture = {path = "../components/texture/core"}
rendiation-texture-packer = {path = "../components/texture/packer"}
webgpu = {package = "rendiation-webgpu", path = "../webgpu"}
winit = {version = "0.26.0"}

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4.28"
console_error_panic_hook = "0.1.6"
web-sys = { version = "0.3.53"}
instant = "0.1.12"

