[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-renderable-mesh"
version = "0.1.0"

[dependencies]
bytemuck = "1.4.1"
soa_derive = "0.8.1"

rendiation-algebra = {path = "../../../math/algebra"}
rendiation-geometry = {path = "../../../math/geometry"}

space-algorithm = {path = "../../space"}

rendiation-webgpu = {path = "../../../webgpu", optional = true}
shadergraph = {path = "../../../shader/graph"}
incremental = {path = "../../../utils/incremental"}

[features]
webgpu = ["rendiation-webgpu"]
