[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-renderable-mesh"
version = "0.1.0"

[dependencies]
bytemuck = "1.4.1"
once_cell = "1.4.0"
soa_derive = "0.8.1"

rendiation-algebra = {path = "../../../math/algebra"}
rendiation-geometry = {path = "../../../math/geometry"}

space-algorithm = {path = "../../space"}

# rendiation-derives = {path = "../derives", optional = true}
# rendiation-shadergraph = {path = "../shader-graph", optional = true}
# rendiation-webgpu = {path = "../ral/backend/webgpu", optional = true}

log = "0.4"
rendiation-webgpu = {path = "../../../webgpu", optional = true}
shadergraph = {path = "../../../shader/graph", optional = true}

[features]
shader = ["shadergraph"]
webgpu = ["rendiation-webgpu"]
