[package]
authors = ["MikiAlex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-texture-packer"
version = "0.1.0"

[dependencies]
rendiation-texture = {path = "../core"}
linked-hash-map = "0.5.4"
etagere = "0.2.6"