[package]
authors = ["MikiAlex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-scene-fusion"
version = "0.1.0"

[dependencies]
arena = {path = "../../utils/arena"}
arena-graph = {path = "../../utils/arena-graph"}
bytemuck = {version = "1.4.1", features = ["derive"]}
log = "0.4"
rendiation-algebra = {path = "../../math/algebra"}
rendiation-geometry = {path = "../../math/geometry"}
rendiation-renderable-mesh = {path = "../../components/mesh/renderable", features = ["webgpu"]}
rendiation-scene-core = {path = "../core"}
rendiation-scene-raytracing = {path = "../raytracing"}
rendiation-scene-webgpu = {path = "../webgpu"}
rendiation-texture = {path = "../../components/texture/core", features = ["webgpu"]}
rendiation-webgpu = {path = "../../webgpu"}
space-algorithm = {path = "../../components/space"}
tree = {path = "../../utils/tree"}
