[package]
edition = "2021"
name = "rendiation-scene-gltf-exporter"
version = "0.0.1"

[dependencies]
gltf = "1.2.0"
gltf-json = "1.2.0"
incremental = {path = "../../../../utils/incremental"}
rendiation-renderable-mesh = {path = "../../../../components/mesh/renderable"}
rendiation-scene-core = {path = "../../../core"}
rendiation-texture = {path = "../../../../components/texture/core"}
tree = {path = "../../../../utils/tree"}
