[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2018"
name = "shader-derives"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
glsl = "6.0.1"
proc-macro2 = "1.0.4"
quote = "1.0.2"
syn = "1.0.11"
proc-macro-faithful-display = "0.1.0"
