[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-shader-derives"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }

[lints]
workspace = true
