[package]
authors = ["MikiAlex <18516340862@163.com>"]
edition = "2021"
name = "viewer"
version = "0.1.0"

[dependencies]
bytemuck = { workspace = true, features = ["derive"] }
env_logger = "0.8.4"
futures = { workspace = true, features = ["thread-pool"] }

dirs = "4.0.0"
image = "*"
png = "*"
rfd = "0.14.0"
fast-hash-collection = { path = "../../utility/fast-hash-collection" }
heap-tools = { path = "../../utility/heap-tools" }
log = { workspace = true }
pin-project = { workspace = true }
rayon = { workspace = true }
reactive = { path = "../../utility/reactive" }
rendiation-algebra = { path = "../../math/algebra" }
rendiation-generative-texture = { path = "../../content/texture/generative" }
rendiation-texture-gpu-process = { path = "../../content/texture/gpu-process" }
rendiation-geometry = { path = "../../math/geometry" }
rendiation-mesh-core = { path = "../../content/mesh/core" }
rendiation-mesh-generator = { path = "../../content/mesh/generator" }
rendiation-controller = { path = "../../extension/controller" }
rendiation-scene-core = { path = "../../scene/core" }
rendiation-shader-api = { path = "../../shader/api" }
rendiation-texture = { path = "../../content/texture/core" }
database = { path = "../../utility/database" }
rendiation-webgpu = { path = "../../platform/graphics/webgpu" }

egui = "0.26"
egui-wgpu = "0.26.0"
egui-winit = "0.26.0"
winit = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
wasm-bindgen-futures = "0.4.28"

[features]
heap-debug = ["heap-tools/enabled"]
webgl = ["rendiation-webgpu/webgl"]

[lints]
workspace = true
