[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-view-override-model"
version = "0.1.0"

[dependencies]
rendiation-algebra = { path = "../../math/algebra" }
webgpu = { package = "rendiation-webgpu", path = "../../platform/graphics/webgpu" }

[lints]
workspace = true
